server:
  port: 7777
  url: localhost:7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room
    username: pradip
    password: PradipAws@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: pradip.inexture@gmail.com
    password: papphlduhnxgueqs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  resources:
    static-locations: classpath:/static/
jwt:
  app:
    jwtSecret: room-management-system
    jwtExpirationMs: 3600000

# Quartz
org:
  quartz:
    scheduler:
      instanceName: SampleJobScheduler
      instanceId: AUTO
      idleWaitTime: 10000
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 4
      threadPriority: 5
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      tablePrefix: QRTZ_
      misfireThreshold: 60000
      isClustered: false
      maxMisfiresToHandleAtATime: 10
      useProperties: true
    jobStore.dataSource: mySql
    dataSource.mySql:
      driver: com.mysql.cj.jdbc.Driver
      URL: jdbc:mysql://localhost:3306/room
      user: pradip
      password: PradipAws@123
      maxConnections: 10
      idleConnectionValidationSeconds: 50
      validationQuery: "select 0 from dual"
      maxIdleTime: 60